// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KulaMVC.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    [Migration("20220220133252_AddedModuleCourse")]
    partial class AddedModuleCourse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");
#pragma warning restore 612, 618
        }
    }
}
