// <auto-generated />
using System;
using KulaMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KulaLearnMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231104233351_InitialMigrationWithSeeds")]
    partial class InitialMigrationWithSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("KulaMVC.Models.Course", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionID")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uploader")
                        .HasColumnType("TEXT");

                    b.Property<int>("published")
                        .HasColumnType("INTEGER");

                    b.Property<int>("visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            CollectionID = "1",
                            CreatedAt = 1699140830,
                            ImageUrl = "https://example.com/course1.jpg",
                            ShortDescription = "Explore the world of web development.",
                            Title = "Web Development Fundamentals",
                            Uploader = "John Doe",
                            published = 0,
                            visibility = 1
                        },
                        new
                        {
                            ID = "2",
                            CollectionID = "2",
                            CreatedAt = 1699140830,
                            ImageUrl = "https://example.com/course2.jpg",
                            ShortDescription = "Learn the basics of programming.",
                            Title = "Introduction to Programming",
                            Uploader = "Jane Smith",
                            published = 0,
                            visibility = 1
                        },
                        new
                        {
                            ID = "3",
                            CollectionID = "3",
                            CreatedAt = 1699140830,
                            ImageUrl = "https://example.com/course3.jpg",
                            ShortDescription = "Dive into the world of data science.",
                            Title = "Data Science Essentials",
                            Uploader = "Alice Johnson",
                            published = 0,
                            visibility = 1
                        });
                });

            modelBuilder.Entity("KulaMVC.Models.Module", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionID")
                        .HasColumnType("TEXT");

                    b.Property<int>("Iat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("LongDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uploader")
                        .HasColumnType("TEXT");

                    b.Property<string>("Video")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Module");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            CollectionID = "1",
                            Iat = 1699140830,
                            Language = "English",
                            LongDescription = "In this module, you will embark on a journey into the exciting world of web development. You'll learn the fundamentals of HTML, CSS, and JavaScript, the three core technologies that power the web. By the end of this module, you'll have the foundational knowledge to create your own web pages and start your web development adventure.",
                            ShortDescription = "Begin your journey into web development.",
                            Title = "Getting Started with Web Development",
                            Uploader = "John Doe",
                            Video = "web-dev-intro.mp4"
                        },
                        new
                        {
                            ID = "2",
                            CollectionID = "1",
                            Iat = 1699140830,
                            Language = "English",
                            LongDescription = "## Master the Art of Web Page Styling\nIn this comprehensive module, you will dive deep into the world of Cascading Style Sheets (CSS). CSS is the key to making your web pages visually appealing, and it plays a crucial role in creating stunning and user-friendly designs. Whether you're a web developer or a designer, mastering CSS is essential for creating modern, responsive web pages.\n\n### Topics Covered\n1. **Introduction to CSS**: Begin by understanding the core concepts of CSS, including selectors and properties. Learn how to create your style rules and link CSS to your HTML documents.\n2. **Box Model**: Delve into the CSS box model, which defines how elements are rendered in web browsers. Learn how to control dimensions, margins, and padding for precise layout design.\n3. **Layout and Positioning**: Explore different layout techniques, such as float, flexbox, and grid. Discover how to control the positioning of elements on your web pages for a responsive design.\n4. **Typography and Color**: Dive into text formatting, font styling, and color choices to make your content visually appealing and readable.\n5. **Transitions and Animations**: Learn how to add animations and transitions to your web elements, making your pages interactive and engaging.\n\n### Practical Skills\nBy the end of this module, you'll have practical skills that allow you to:\n- Create beautifully styled web pages\n- Implement responsive layouts\n- Enhance user experience through interactive elements\n\nWhether you're a beginner or an experienced developer, this module will elevate your web design and development skills to the next level. Join us on this journey to becoming a CSS master!",
                            ShortDescription = "Learn how to style your web pages with CSS.",
                            Title = "CSS Styling for Web Pages",
                            Uploader = "John Doe",
                            Video = "css-styling.mp4"
                        },
                        new
                        {
                            ID = "3",
                            CollectionID = "1",
                            Iat = 0,
                            Language = "English",
                            LongDescription = "## Unlock the Power of Data Science\nIn this in-depth module, you will explore the exciting and transformative world of data science. Data science is at the heart of modern decision-making and insights, and it plays a pivotal role across industries. Whether you're a budding data scientist or a professional looking to harness data-driven insights, this module is your gateway to mastering data science techniques.\n\n### Topics Covered\n1. **Data Analysis**: Begin with the fundamentals of data analysis. Learn how to collect, clean, and explore data to derive meaningful insights.\n2. **Statistical Analysis**: Delve into statistical methods to make data-driven decisions. Understand concepts like probability, hypothesis testing, and regression analysis.\n3. **Machine Learning**: Explore machine learning algorithms for predictive analytics, classification, and clustering. Learn how to implement models and evaluate their performance.\n4. **Data Visualization**: Master the art of data visualization using tools like Matplotlib and Seaborn. Create compelling visuals to communicate data insights effectively.\n5. **Big Data and AI**: Discover how to work with big data technologies and harness the power of artificial intelligence to solve complex problems.\n\n### Practical Skills\nBy the end of this module, you'll have practical skills that allow you to:\n- Analyze and interpret data\n- Make data-driven decisions\n- Develop machine learning models\n- Create meaningful data visualizations\n\nWhether you're a data science enthusiast or a professional aiming to advance your career, this module will equip you with the knowledge and skills to tackle real-world data challenges with confidence. Join us on this journey to master data science techniques!",
                            ShortDescription = "Dive deep into the world of data science.",
                            Title = "Mastering Data Science Techniques"
                        },
                        new
                        {
                            ID = "4",
                            CollectionID = "2",
                            Iat = 1699140830,
                            Language = "English",
                            LongDescription = "## Mastering JavaScript for Web Development\nWelcome to the fascinating world of JavaScript! In this module, we will dive deep into JavaScript fundamentals. JavaScript is the backbone of interactivity on the web, and understanding it is essential for any web developer.\n\n### Topics Covered\n1. **JavaScript Basics**: Get started with JavaScript syntax, variables, and data types. Learn how to write your first JavaScript code.\n2. **Control Structures**: Explore if statements, loops, and switch statements. Understand how to control the flow of your code.\n3. **Functions and Objects**: Dive into functions, objects, and their role in building complex web applications. Learn about the Document Object Model (DOM).\n4. **Event Handling**: Understand how to handle user interactions and create responsive web pages. Work with event listeners and event-driven programming.\n5. **Asynchronous JavaScript**: Explore asynchronous programming, promises, and AJAX to create dynamic and responsive web applications.\n\n### Practical Skills\nBy the end of this module, you'll have practical skills that allow you to:\n- Write JavaScript code for web applications\n- Create dynamic and interactive web pages\n- Handle user interactions and events\n- Work with the DOM to manipulate web content\n\nWhether you're new to JavaScript or want to deepen your knowledge, this module will prepare you to create interactive and engaging web applications.",
                            Title = "JavaScript Fundamentals",
                            Uploader = "Jane Smith",
                            Video = "javascript-fundamentals.mp4"
                        },
                        new
                        {
                            ID = "5",
                            CollectionID = "2",
                            Iat = 1699140830,
                            Language = "English",
                            LongDescription = "## Crafting Stunning Responsive Web Pages\nResponsive web design is crucial in today's digital landscape. In this module, you will master the art of creating web pages that adapt seamlessly to various devices and screen sizes. You'll learn the principles, techniques, and best practices for building responsive websites.\n\n### Topics Covered\n1. **Understanding Responsive Design**: Learn the fundamentals of responsive design and why it's important in the mobile-first era.\n2. **Media Queries**: Dive into CSS media queries to control the layout and styling of your web pages based on screen characteristics.\n3. **Flexible Layouts**: Explore flexible grid systems and flexbox to create fluid and adaptable page layouts.\n4. **Responsive Images**: Learn how to handle responsive images and optimize them for various devices and resolutions.\n5. **Testing and Debugging**: Discover tools and techniques for testing and debugging your responsive designs across multiple devices.\n\n### Practical Skills\nBy the end of this module, you'll have practical skills that allow you to:\n- Create responsive web designs that work on various devices\n- Optimize images for different screen sizes\n- Test and troubleshoot responsive layouts\n\nWhether you're a web developer or a designer, this module will empower you to create web pages that provide an excellent user experience on desktops, tablets, and mobile devices.",
                            Title = "Responsive Web Design",
                            Uploader = "Jane Smith",
                            Video = "responsive-design.mp4"
                        },
                        new
                        {
                            ID = "6",
                            CollectionID = "2",
                            Iat = 1699140830,
                            Language = "English",
                            LongDescription = "## Ensuring Inclusive Web Experiences\nWeb accessibility is a fundamental aspect of web development. In this module, you will learn the essentials of making web content accessible to people with disabilities. Creating inclusive web experiences is not only a legal requirement but also a moral and ethical obligation.\n\n### Topics Covered\n1. **Introduction to Web Accessibility**: Understand the importance of web accessibility and its impact on various user groups.\n2. **WCAG Guidelines**: Explore the Web Content Accessibility Guidelines (WCAG) and how they define accessible web content.\n3. **Semantic HTML**: Learn to use semantic HTML elements for improved accessibility and proper document structure.\n4. **Accessible Forms and Multimedia**: Discover best practices for creating accessible forms, images, and multimedia content.\n5. **Testing and Remediation**: Explore tools and techniques for testing and remediating web content to ensure compliance with accessibility standards.\n\n### Practical Skills\nBy the end of this module, you'll have practical skills that allow you to:\n- Create web content that is accessible to all users\n- Understand and apply WCAG guidelines\n- Test and remediate web content for accessibility\n\nWhether you're a web developer, designer, or content creator, this module will equip you with the knowledge and skills to make the web a more inclusive place for everyone.",
                            Title = "Web Accessibility Essentials",
                            Uploader = "Jane Smith",
                            Video = "web-accessibility.mp4"
                        },
                        new
                        {
                            ID = "7",
                            CollectionID = "3",
                            Iat = 1699140830,
                            Language = "English",
                            LongDescription = "## Mastering Data Wrangling for Data Science\nData wrangling is an essential step in the data science process. In this module, you'll learn how to acquire, clean, and preprocess data to make it suitable for analysis. Data quality and preparation are critical to deriving meaningful insights and building accurate models.\n\n### Topics Covered\n1. **Data Acquisition**: Explore various data sources and methods for collecting data. Understand data formats and APIs for data retrieval.\n2. **Data Cleaning**: Learn how to identify and handle missing data, outliers, and inconsistencies in your datasets. Apply techniques for data cleansing.\n3. **Data Transformation**: Discover methods for reshaping, aggregating, and transforming data to prepare it for analysis. Work with tools like Pandas and Numpy.\n4. **Data Integration**: Integrate data from multiple sources and combine datasets to create a unified dataset for analysis.\n5. **Data Quality and Validation**: Ensure data quality and validate your datasets for accuracy and completeness.\n\n### Practical Skills\nBy the end of this module, you'll have practical skills that allow you to:\n- Acquire and clean data from various sources\n- Transform and reshape data for analysis\n- Integrate and validate datasets\n\nWhether you're a data scientist or aspiring to become one, this module will equip you with the skills needed to prepare data for meaningful analysis.",
                            Title = "Data Wrangling and Preprocessing",
                            Uploader = "Alice Johnson",
                            Video = "data-wrangling.mp4"
                        },
                        new
                        {
                            ID = "8",
                            CollectionID = "3",
                            Iat = 1699140830,
                            Language = "English",
                            LongDescription = "## Uncover Insights with Statistical Analysis\nStatistical analysis is a fundamental tool in the data scientist's toolkit. In this module, you'll dive into statistical concepts and techniques to uncover patterns, trends, and insights within your data. Whether you're new to statistics or looking to deepen your knowledge, this module will provide you with the skills to make data-driven decisions.\n\n### Topics Covered\n1. **Descriptive Statistics**: Learn how to describe and summarize data using measures of central tendency and dispersion. Create meaningful visualizations of data.\n2. **Inferential Statistics**: Understand the principles of inferential statistics, hypothesis testing, and confidence intervals.\n3. **Correlation and Regression**: Explore the relationships between variables and learn how to perform regression analysis.\n4. **Statistical Tests**: Learn about different types of statistical tests, including t-tests, ANOVA, and chi-square tests.\n5. **Practical Applications**: Apply statistical analysis to real-world data and make data-driven decisions.\n\n### Practical Skills\nBy the end of this module, you'll have practical skills that allow you to:\n- Analyze data using descriptive and inferential statistics\n- Conduct hypothesis tests and make inferences\n- Apply statistical analysis to solve real-world problems\n\nThis module is designed to empower you with the statistical knowledge and skills needed to make informed decisions based on data analysis.",
                            Title = "Statistical Analysis and Hypothesis Testing",
                            Uploader = "Alice Johnson",
                            Video = "statistical-analysis.mp4"
                        },
                        new
                        {
                            ID = "9",
                            CollectionID = "3",
                            Iat = 1699140830,
                            Language = "English",
                            LongDescription = "## Journey into the World of Machine Learning\nMachine learning is transforming industries and enabling data-driven solutions. In this module, you'll embark on a journey into the fundamentals of machine learning. You'll learn the core concepts, algorithms, and practical applications that make machine learning a powerful tool for data scientists and developers.\n\n### Topics Covered\n1. **Introduction to Machine Learning**: Understand the basics of machine learning, its applications, and the machine learning pipeline.\n2. **Supervised Learning**: Explore supervised learning algorithms, including regression and classification. Learn about decision trees, support vector machines, and more.\n3. **Unsupervised Learning**: Dive into unsupervised learning, clustering, and dimensionality reduction techniques.\n4. **Model Evaluation**: Discover how to evaluate and validate machine learning models using metrics and cross-validation.\n5. **Practical Applications**: Apply machine learning to real-world datasets and solve predictive and classification problems.\n\n### Practical Skills\nBy the end of this module, you'll have practical skills that allow you to:\n- Understand the principles of machine learning\n- Build and evaluate machine learning models\n- Apply machine learning to real-world problems\n\nWhether you're a data scientist, developer, or aspiring to work in machine learning, this module will provide you with the foundation to explore the exciting world of machine learning.",
                            Title = "Machine Learning Fundamentals",
                            Uploader = "Alice Johnson",
                            Video = "machine-learning-fundamentals.mp4"
                        });
                });

            modelBuilder.Entity("KulaMVC.Models.User", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            ID = "2",
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            ID = "3",
                            FirstName = "Alice",
                            LastName = "Johnson"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fab4fac1-c546-41de-aebc-a14da6895711",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            ConcurrencyStamp = "2",
                            Name = "Instructor",
                            NormalizedName = "Instructor"
                        },
                        new
                        {
                            Id = "de7013f0-8790-5417-abh9-e324f91r7442",
                            ConcurrencyStamp = "3",
                            Name = "Student",
                            NormalizedName = "Student"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b74ddd14-6340-4840-95c2-db12554843e5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4550e1d7-81e5-47a2-9426-a25057a92ec0",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fde5af89-e221-4f6c-86a0-8f465bb8b646",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b74ddd14-6340-4840-95c2-db12554843e5",
                            RoleId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
