// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KulaMVC.Migrations.MvcCourses
{
    [DbContext(typeof(MvcCoursesContext))]
    [Migration("20220220134120_AddedModuleCourses2")]
    partial class AddedModuleCourses2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("KulaMVC.Models.Course", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("collectionID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("createdAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("shortDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("uploader")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("KulaMVC.Models.Module", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("collectionID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("iat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("longDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("shortDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("uploader")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("video")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Module");
                });
#pragma warning restore 612, 618
        }
    }
}
